services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: mainlogic-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build: .
    container_name: mainlogic-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Override the AMQP URL to use the internal docker network hostname "rabbitmq" instead of localhost
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
    command: ["npm", "start"]

  worker-location:
    build: .
    container_name: mainlogic-worker-location
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
    command: ["npm", "run", "worker:location:prod"]

  worker-notifications:
    build: .
    container_name: mainlogic-worker-notifications
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
    command: ["npm", "run", "worker:notifications:prod"]

volumes:
  rabbitmq_data:
